name = "svg-to-png"
type = "javascript"
workers_dev = true
account_id = "account_id"
compatibility_date = "2022-02-27"

[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
